# Generated by Django 3.1.3 on 2020-11-10 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the book', max_length=100, verbose_name='Name of the book')),
                ('edition', models.IntegerField(help_text='Edition number', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Edition number')),
                ('publication_year', models.IntegerField(help_text='Publication year of the book', validators=[django.core.validators.MinValueValidator(1800)], verbose_name='Publication year of the book')),
                ('authors', models.ManyToManyField(help_text='List of authors of book', related_name='books', to='authors.Author', verbose_name='Authors of the book')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
    ]
